# Generated by Django 3.1 on 2020-09-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200918_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/static/images/default_image.png', upload_to='blog/static/images', verbose_name='Изображение'),
        ),
    ]
