# Generated by Django 3.1 on 2020-09-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_viewsuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewsUser',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
