# Generated by Django 3.1 on 2020-09-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200920_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sharesUser',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
